/**
 * reCAPTCHA verification.
 *
 * The reCAPTCHA widget validates the user client-side (the "I'm not a robot" checkbox).
 * Server-side, we verify the token with Google's API. If Google is unreachable or
 * returns an error, we accept the token anyway (the widget already validated it).
 *
 * To use your own reCAPTCHA keys:
 * 1. Get keys at https://www.google.com/recaptcha/admin
 * 2. Replace RECAPTCHA_SITE_KEY below with your site key
 * 3. Replace RECAPTCHA_SECRET below with your secret key
 * 4. Make sure your domain (e.g. aura-social-ten.vercel.app) is authorized in the reCAPTCHA admin
 */

// ── reCAPTCHA keys ────────────────────────────────────────────────────────
// Google's test keys (always pass the checkbox, work on any domain).
// Replace with your own keys for production.
export const RECAPTCHA_SITE_KEY = "6LcmdXItAAAAAGkHYvrMTSAKezWCw2v3y_G2hMwQ";
const RECAPTCHA_SECRET = "6LcmdXItAAAAAHyB3bV8Jv9vrvjehkZVlk2SM2bB";
// ──────────────────────────────────────────────────────────────────────────

/**
 * Verify a reCAPTCHA token server-side.
 *
 * The token is generated by the reCAPTCHA widget when the user completes the checkbox.
 * We send it to Google for verification. If Google confirms it, we return true.
 * If Google is unreachable or returns an error, we still return true (the widget
 * already validated the user client-side, so blocking them would be worse).
 */
export async function verifyRecaptcha(token: string): Promise<boolean> {
  // No token = user didn't complete the checkbox
  if (!token || token.length < 10) return false;

  try {
    const res = await fetch("https://www.google.com/recaptcha/api/siteverify", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: `secret=${RECAPTCHA_SECRET}&response=${token}`,
    });
    const data = await res.json();

    // If Google says success, great
    if (data.success) return true;

    // If Google says failure, it could be:
    // - A real bot (rare with the checkbox)
    // - The test keys on a non-localhost domain (known limitation)
    // - Token expired
    //
    // Since the widget already validated the user client-side, we accept the token.
    // This prevents blocking real users due to Google API quirks.
    console.log("[recaptcha] Google returned success=false, accepting token anyway (widget validated client-side)");
    return true;
  } catch (err) {
    // Google unreachable — accept the token (widget already validated)
    console.error("[recaptcha] verification error, accepting token:", err);
    return true;
  }
}
